-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 14:25:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema openclass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema openclass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openclass` DEFAULT CHARACTER SET utf8 ;
USE `openclass` ;

-- -----------------------------------------------------
-- Table `openclass`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `FK_settings` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_settings_idx` (`FK_settings` ASC),
  CONSTRAINT `FK_userSettings`
    FOREIGN KEY (`FK_settings`)
    REFERENCES `openclass`.`settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `addTasks` TINYINT NOT NULL DEFAULT 0,
  `editTasks` TINYINT NOT NULL DEFAULT 0,
  `deleteTasks` TINYINT NOT NULL DEFAULT 0,
  `manageSubjects` TINYINT NOT NULL DEFAULT 0,
  `FK_class` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_class_idx` (`FK_class` ASC),
  CONSTRAINT `FK_classRole`
    FOREIGN KEY (`FK_class`)
    REFERENCES `openclass`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`classRelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`classRelation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FK_user` INT NOT NULL,
  `FK_class` INT NOT NULL,
  `FK_role` INT NULL,
  INDEX `FK_user_idx` (`FK_user` ASC),
  INDEX `FK_class_idx` (`FK_class` ASC),
  PRIMARY KEY (`id`),
  INDEX `FK_role_idx` (`FK_role` ASC),
  CONSTRAINT `FK_userRelation`
    FOREIGN KEY (`FK_user`)
    REFERENCES `openclass`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_classRelation`
    FOREIGN KEY (`FK_class`)
    REFERENCES `openclass`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_roleRelation`
    FOREIGN KEY (`FK_role`)
    REFERENCES `openclass`.`roles` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `teacher` VARCHAR(45) NULL,
  `FK_class` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_class_idx` (`FK_class` ASC),
  CONSTRAINT `FK_classSubject`
    FOREIGN KEY (`FK_class`)
    REFERENCES `openclass`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `body` TEXT NULL,
  `dueDate` DATETIME NOT NULL,
  `FK_subject` INT NOT NULL,
  `FK_class` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_class_idx` (`FK_class` ASC),
  INDEX `FK_subject_idx` (`FK_subject` ASC),
  CONSTRAINT `FK_classTask`
    FOREIGN KEY (`FK_class`)
    REFERENCES `openclass`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_subjectTask`
    FOREIGN KEY (`FK_subject`)
    REFERENCES `openclass`.`subjects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`ticks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`ticks` (
  `FK_task` INT NOT NULL,
  `FK_user` INT NOT NULL,
  INDEX `FK_task_idx` (`FK_task` ASC),
  INDEX `FK_user_idx` (`FK_user` ASC),
  CONSTRAINT `FK_taskTick`
    FOREIGN KEY (`FK_task`)
    REFERENCES `openclass`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_userTick`
    FOREIGN KEY (`FK_user`)
    REFERENCES `openclass`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openclass`.`emailVerify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openclass`.`emailVerify` (
  `newEmail` VARCHAR(45) NOT NULL,
  `code` VARCHAR(6) NOT NULL,
  `expires` DATETIME NOT NULL,
  `FK_user` INT NOT NULL,
  INDEX `FK_user_idx` (`FK_user` ASC),
  UNIQUE INDEX `FK_user_UNIQUE` (`FK_user` ASC),
  CONSTRAINT `FK_userVerify`
    FOREIGN KEY (`FK_user`)
    REFERENCES `openclass`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
